import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className="bg-black text-white flex flex-col min-h-screen">
    <main className="flex-1">{children}</main>
    <footer className="text-sm text-gray-500 text-center py-6 border-t border-gray-800">
    &copy; {new Date().getFullYear()} Aftermath Technologies. Created by Brad Kinnard.
    </footer>
    </body>

    </html>
  );
}
